### PR TITLE
Added devantech_change_addr.cpp

### PR DESCRIPTION
**Pull request by fgiaimo**

### CODE REVIEW

**Review by chrberger — COMMENTED** [review]
Don’t we need a few milliseconds of delay between the steps?

**Comment by fgiaimo** [comment]
I can check the datasheet again and add them if necessary. However it
worked for me like this.

Federico Giaimo

On Feb 27, 2018 17:30, "Christian Berger" <notifications@github.com> wrote:

*@chrberger* commented on this pull request.

Don’t we need a few milliseconds of delay between the steps?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chalmers-revere/opendlv.scaledcars/pull/15#pullrequestreview-99755247>,
or mute the thread

**Comment by fgiaimo** [comment]
I found an implementation that adds the delays (https://custom-build-robots.com/raspberry-pi-elektronik/raspberry-pi-und-der-srf08-ultraschallsensor-mit-i2c-bus-zur-entfernungsmessung/286) and an implementation that does not add them (https://os.mbed.com/users/brentdekker/code/SRF08/docs/a11bd4ea3c18/SRF08_8cpp_source.html#l00129). No info on the datasheet unfortunately. 
It looks to me that they may be a safety precaution but not _really_ necessary, or it would be stated somewhere.

**Comment by chrberger** [comment]
I suggest that we add the delays - just in case

**Comment by fgiaimo** [comment]
Sure.

On Feb 28, 2018 10:47, "Christian Berger" <notifications@github.com> wrote:

I suggest that we add the delays - just in case

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chalmers-revere/opendlv.scaledcars/pull/15#issuecomment-369185007>,
or mute the thread

**Comment by fgiaimo** [comment]
Done

**Comment by chrberger** [comment]
LGTM

**Comment by fgiaimo** [comment]
Can't merge until it's approved :)

**Review by chrberger — APPROVED** [review]
Approved

**Review by bjornborg — APPROVED** [review]
LGTM

**Pull request merged**
